//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassQuotaTotalFee
    {
        public int ClassQuotaTotalFeeId { get; set; }
        public int ClassId { get; set; }
        public byte QuotaId { get; set; }
        public decimal TotalFee { get; set; }
        public byte AcademicYearId { get; set; }
        public bool IsActive { get; set; }
    }
}
