//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeeType()
        {
            this.ClassFeeBreakups = new HashSet<ClassFeeBreakup>();
        }
    
        public int FeeTypeId { get; set; }
        public string FeeTypeName { get; set; }
        public string FeeTypeDisplayName { get; set; }
        public int FeeFactor { get; set; }
        public bool IsActive { get; set; }
        public byte Priority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassFeeBreakup> ClassFeeBreakups { get; set; }
    }
}
