//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FMSEntities : DbContext
    {
        public FMSEntities()
            : base("name=FMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassFeeBreakup> ClassFeeBreakups { get; set; }
        public virtual DbSet<FeeType> FeeTypes { get; set; }
        public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<StudentPayment> StudentPayments { get; set; }
        public virtual DbSet<StudentQuota> StudentQuotas { get; set; }
        public virtual DbSet<AcademicYear> AcademicYears { get; set; }
        public virtual DbSet<StudentStatus> StudentStatus1 { get; set; }
        public virtual DbSet<FMSRole> FMSRoles { get; set; }
        public virtual DbSet<FMSUser> FMSUsers { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<RoleModule> RoleModules { get; set; }
        public virtual DbSet<UserSchool> UserSchools { get; set; }
        public virtual DbSet<ClassQuotaTotalFee> ClassQuotaTotalFees { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
