//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.StudentPayments = new HashSet<StudentPayment>();
        }
    
        public long ReceiptId { get; set; }
        public string ReceiptName { get; set; }
        public decimal Amount { get; set; }
        public byte PaymentModeId { get; set; }
        public string ChequeNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public decimal Balance { get; set; }
        public byte AcademicYearId { get; set; }
    
        public virtual PaymentMode PaymentMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPayment> StudentPayments { get; set; }
        public virtual AcademicYear AcademicYear { get; set; }
    }
}
