//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPayment
    {
        public long StudentPaymentId { get; set; }
        public int StudentId { get; set; }
        public long ReceiptId { get; set; }
        public int ClassFeeBreakupId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public byte AcademicYearId { get; set; }
    
        public virtual ClassFeeBreakup ClassFeeBreakup { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual Student Student { get; set; }
    }
}
