//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentPayments = new HashSet<StudentPayment>();
        }
    
        public int StudentId { get; set; }
        public string StudentRegistartionNo { get; set; }
        public int ClassId { get; set; }
        public int SchoolId { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string StudentLastName { get; set; }
        [Required]
        public string StudentFirstName { get; set; }
        public string StudentMiddleName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string BirthAddress { get; set; }
        public string ReligionAndCast { get; set; }
        public byte StudentQuotaId { get; set; }
        public string ParentLastName { get; set; }
        public string ParentFirstName { get; set; }
        public string ParentMiddleName { get; set; }
        [Required]
        public string CurrentAddress { get; set; }
        [Required]
        public string CantactNumbers { get; set; }
        public string PermanentAddress { get; set; }
        public string ParentOccuapation { get; set; }
        public Nullable<decimal> AnnualIncom { get; set; }
        public string RelationWithStudent { get; set; }
        public string PreviousSchool { get; set; }
        public string LastPassedClass { get; set; }
        public string LastPassedYear { get; set; }
        public Nullable<int> LastClassMarks { get; set; }
        public Nullable<int> LastClassTotalMarks { get; set; }
        public Nullable<decimal> LastClassPercentage { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public byte AdmissionAcademicYearId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte StatusId { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual Class Class { get; set; }
        public virtual School School { get; set; }
        public virtual StudentQuota StudentQuota { get; set; }
        public virtual StudentStatus StudentStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPayment> StudentPayments { get; set; }
    }
}
